package HomePractice.LeedCode.String;

import java.util.Scanner;

/* 389.
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

 */
public class FindTheDifference {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter the 1st string:");
        String str1 = sc.next();
        System.out.print("Enter the 2nd string : ");
        String str2 = sc.next();
        System.out.println("Difference character is : "+findTheDifference(str1,str2));
    }
    public static char findTheDifference(String s, String t) {
        char c=0;
        for(char cs:s.toCharArray())
        {
            c^=cs;
        }
        for(char ct:t.toCharArray())
        {
            c^=ct;
        }
        return c;
    }
}
